#!/usr/bin/php
<?php

new ShellyDevice();

class ShellyDevice {

	public $Device;

	public function __construct() {

		// define options for cli call
		$options = getopt("h:u::p::w::c::H::", array("host:", "user::", "password::","warning::", "critical::" , "help"));

		// If help or the shortcut H is set print the help message
		if(isset($options['help']) || isset($options['H'])) {
			echo "check_shelly is a nagios compatible check to monitor the health of shelly hardware.\n\n";
			echo "You can run it for example with:\n";
			echo "./check_shelly -h <SHELLY_IP>\n\n";
			echo "If you have authentication enabled then you have to run:\n";
			echo "./check_shelly -h <SHELLY_IP> -u <USER> -p <PASSWORD>\n\n";
			echo "To change the warning or the critical value you can pass in -w or -c to change it\n";
			echo "./check_shelly -h <SHELLY_IP> -w <WARNING> -c <CRITICAL>\n";
			echo "\n\nThe critical or warning threshold refers to the cpu usage OR the filesystem usage.";
			echo "Available flags:\n";
			echo "\t--host\t\t-h\t(required flag) The hostname or IP-Adress of the shelly\n";
			echo "\t--user\t\t-u\tThe username for the Shelly, when the shelly needs authentication\n";
			echo "\t--password\t-p\tThe password for the Shelly, when the shelly needs authentication\n";
			echo "\t--warning\t-w\tThe warning threshold. If the shelly has more RAM or disk usage then  the check is warning\n";
			echo "\t--critical\t-c\tThe critical threshold. If the shelly has more RAM or disk usage then  the check is critical\n";
			echo "\t--help\t\t-h\tprints this message\n";
			exit(0);
		}
		// If no host is set print an error
		if(!isset($options['host']) && !isset($options['h'])) {
			echo "parameter -h || --host is missing \n";
			exit(3);
		}
		$host =  isset($options['host']) ? $options['host'] : $options['h'];
		$user =  isset($options['user']) ? $options['user'] : (isset($options['u']) ? $options['u'] : false);
		$password =  isset($options['password']) ? $options['password'] : (isset($options['p']) ? $options['p'] : false);
		
		$this->Device['check']['warning'] =  isset($options['warning']) ? $options['warning'] : (isset($options['w']) ? $options['w'] : 90);
		$this->Device['check']['critical'] =  isset($options['critical']) ? $options['critical'] : (isset($options['c']) ? $options['c'] : 95);

		$this->_discoverShelly($host, $user, $password);
		$this->_renderOutput();
	}

	private function _discoverShelly($host, $user = false, $password = false) {
		// discover status and settings
		$shellystatus = "http://" . $host . '/status';
		$shellysettings  = "http://" . $host . '/settings';

		//Initialize a Curl handler
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_USERAGENT, 'curl');
		curl_setopt($ch, CURLOPT_TIMEOUT, 5); //timeout after 5 seconds
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_USERPWD, "$user:$password");
		curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
		curl_setopt($ch, CURLOPT_URL, $shellystatus);
		$this->Device['status'] = json_decode(curl_exec ($ch), true);

		// discovery failed, probably a username / password issue..
		if (!is_array($this->Device['status']))	{
			echo 'UNKNOWN: Shelly health status is unknown. The device is probably protected with username and password.';
			exit(3);
		}

		if (isset($this->Device['status']['meters']) &&  is_array($this->Device['status']['meters'])) {
			$this->Device['meters'] = $this->Device['status']['meters'];
		}
		else 
			$this->Device['meters'] = '';
		
		if (isset($this->Device['status']['temperature'])) {
			$this->Device['temperature'] = $this->Device['status']['temperature'];
		}

		if (isset($this->Device['status']['emeters']) &&  is_array($this->Device['status']['emeters']))	{
			$this->Device['emeters'] = $this->Device['status']['emeters'];
		}
		else 
			$this->Device['emeters'] = '';

		curl_setopt($ch, CURLOPT_URL, $shellysettings);
		$this->Device['settings'] = json_decode(curl_exec ($ch), true);
		$this->Device['uptime'] = secondsToTime($this->Device['status']['uptime']);
		$this->Device['uptime_ts'] = $this->Device['status']['uptime'];

		$this->Device['check']['exit_code'] = 0;
		
		// calculate ram usage
		$this->Device['ram']['ram_total'] = $this->Device['status']['ram_total'];
		$this->Device['ram']['ram_free'] = $this->Device['status']['ram_free'];
		$this->Device['ram']['ram_used'] = $this->Device['status']['ram_total'] - $this->Device['status']['ram_free'];
		$this->Device['ram']['usage'] = round($this->Device['ram']['ram_used'] * 100 / $this->Device['ram']['ram_total'], 2);

		// calculate filesystem usage
		$this->Device['fs']['fs_size'] = $this->Device['status']['fs_size'];
		$this->Device['fs']['fs_free'] = $this->Device['status']['fs_free'];
		$this->Device['fs']['fs_used'] = $this->Device['status']['fs_size'] - $this->Device['status']['fs_free'];
		$this->Device['fs']['usage'] = round($this->Device['fs']['fs_used'] * 100 / $this->Device['fs']['fs_size'], 2);

		if ($this->Device['ram']['usage'] > $this->Device['check']['warning'] || $this->Device['fs']['usage'] > $this->Device['check']['warning'] )
			$this->Device['check']['exit_code'] = 1;
		
		if ($this->Device['ram']['usage'] > $this->Device['check']['critical'] || $this->Device['fs']['usage'] > $this->Device['check']['critical'] )
			$this->Device['check']['exit_code'] = 2;
	}

	// _renderOutput will generate the nagios default output with performance data
	private function _renderOutput() {
		// generate the plugin output
		if ($this->Device['check']['exit_code'] == 0)
			echo 'OK: ' . $this->Device['settings']['device']['hostname'] . ' - Type: ' . $this->Device['settings']['device']['type']  . ' (Uptime: ' . $this->Device['uptime']. ') is healthy.';

		if ($this->Device['check']['exit_code'] == 1)
			echo 'WARNING: ' . $this->Device['settings']['device']['hostname'] . ' - Type: ' . $this->Device['settings']['device']['type']  . ' (Uptime: ' . $this->Device['uptime']. ') reported problems. Please check details...';
	
		if ($this->Device['check']['exit_code'] == 2)
			echo 'CRITICAL: ' . $this->Device['settings']['device']['hostname'] . ' - Type: ' . $this->Device['settings']['device']['type']  . ' (Uptime: ' . $this->Device['uptime']. ') reported problems. Please check details...';

		if (isset($this->Device['status']['inputs'])) {
			foreach ($this->Device['status']['inputs'] as $input => $state) {
				echo "\n Input " .$input . ': ' . ($state == 1 ? "on" : "off");  
			}
		}
		if (isset($this->Device['status']['relays'])) {
			foreach ($this->Device['status']['relays'] as $relay => $state) {
				echo "\n Relay " .$relay . ': ' . ($state['ison'] == true ? "on" : "off");  
			}
		}
		if (isset($this->Device['status']['lights'])) {
			foreach ($this->Device['status']['lights'] as $light => $state) {
				echo "\n Light " .$light . ': ' . ($state['ison'] == true ? "on" : "off");  
			}
		}
		// add default performance data => ramusage and fsusage
		echo '|';
		echo ' ram='. $this->Device['ram']['ram_used'] . ';;;0;'. $this->Device['ram']['ram_total'];
		echo ' ramusage='. $this->Device['ram']['usage'] . '%;' . $this->Device['check']['warning'] . ';' . $this->Device['check']['critical'] . ';0;100';

		echo ' fs='. $this->Device['fs']['fs_used'] . ';;;0;'. $this->Device['fs']['fs_size'];
		echo ' fsusage='. $this->Device['fs']['usage'] . '%;' . $this->Device['check']['warning'] . ';' . $this->Device['check']['critical'] . ';0;100';

		// if meters is set, then add the meters performance data to the output
		if (is_array($this->Device['meters'])) {
			foreach($this->Device['meters'] as $key => $value) {
				echo ' power' . $key . '=' . $value['power'] . ';;;;';
			}
		}

		// if emeters is set, then add the emeters performance data to the output
		if (is_array($this->Device['emeters'])) {
			foreach($this->Device['emeters'] as $key => $value) {
				echo ' power' . $key . '=' . $value['power'] . ';;;;';
				echo ' reactive' . $key . '=' . $value['reactive'] . ';;;;';
				echo ' voltage' . $key . '=' . $value['voltage'] . ';;;;';
			}
		}

		// if temperature is set, then add the temperature performance data to the output
		if (isset($this->Device['temperature']))
			echo ' temperature=' . $this->Device['temperature'] . ';;;;';
		echo "\n";
	}

}

// seconds to time parses an amount of seconds to a formatted output of days, hours, minutes and seconds
function secondsToTime($seconds) 
{
    $dtF = new \DateTime('@0');
    $dtT = new \DateTime("@$seconds");
    return $dtF->diff($dtT)->format('%a days, %h hours, %i minutes and %s seconds');
}
